language: node_js
cache:
        directories:
                - ~/.npm
node_js:
        - '12'
git:
        depth: 3
script:
        - yarn build:prod
deploy:
        provider: pages
        edge: true
        skip_cleanup: true
        keep-history: true
        github-token: $GITHUB_TOKEN
        local-dir: dist/
        target-branch: gh-pages
        commit_message: "Deploy Release"
        on:
                branch: master
